# Generated by Django 3.0.4 on 2020-03-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='items',
            field=models.ManyToManyField(blank=True, through='main.BasketItems', to='main.Shape'),
        ),
    ]
