# Generated by Django 3.0.4 on 2020-04-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200319_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='has_changed',
            field=models.BooleanField(default=False),
        ),
    ]
